// Status color mapping
export const statusColors = {
  "on-time": "bg-green-500",
  "probable-delay": "bg-yellow-500",
  "imminent-delay": "bg-amber-500",
  aog: "bg-red-500",
  "in-progress": "bg-blue-500",
  pending: "bg-purple-500",
  critical: "bg-red-700",
}

export const statusLabels = {
  "on-time": "On Time",
  "probable-delay": "Probable Delay",
  "imminent-delay": "Imminent Delay",
  aog: "AOG",
  "in-progress": "In Progress",
  pending: "Pending",
  critical: "Critical",
}

// Station information
export const stations = [
  { code: "YYZ", name: "Toronto Pearson International Airport" },
  { code: "YYC", name: "Calgary International Airport" },
  { code: "YVR", name: "Vancouver International Airport" },
  { code: "YOW", name: "Ottawa Macdonald-Cartier International Airport" },
  { code: "YEG", name: "Edmonton International Airport" },
  { code: "YHZ", name: "Halifax Stanfield International Airport" },
  { code: "YUL", name: "Montréal-Pierre Elliott Trudeau International Airport" },
]

export type Aircraft = {
  id: string
  registration: string
  type: string
  status: "active" | "maintenance" | "aog" | "scheduled"
  location: string
  gate?: string
  flightPhase?: string
  nextFlight?: {
    flightNumber: string
    destination: string
    departureTime: string
    arrivalTime: string
    status: "on-time" | "delayed" | "cancelled" | "probable-delay" | "imminent-delay"
    scheduledDeparture?: string
    estimatedDeparture?: string
    scheduledArrival?: string
    estimatedArrival?: string
    delayMinutes?: number
    delayReason?: string
  }
  maintenanceStatus?: {
    type: string
    dueDate: string
    completionPercentage: number
    estimatedCompletion?: string
    assignedTechnicians?: string[]
  }
  currentFault?: {
    id: string
    description: string
    system: string
    subsystem: string
    ataChapter: string
    estimatedResolution: string
    reportedBy: string
    assignedTo: string
    status: string
    priority: string
    impactedFlights?: string[]
    delayImpact?: string
    reportedTime?: string
    impact?: string
  }
  technicalInfo?: {
    manufacturer: string
    engineType: string
    totalFlightHours: number
    totalCycles?: number
    manufactureDate?: string
    lastCCheck?: string
    nextCCheck?: string
  }
  defects?: any[]
}

// Mock aircraft data
export const aircraftData: Aircraft[] = [
  {
    id: "AC001",
    registration: "C-FGDT",
    type: "Boeing 777-300ER",
    status: "aog",
    location: "YVR",
    gate: "D73",
    flightPhase: "Departing",
    nextFlight: {
      flightNumber: "AC016",
      destination: "HKG",
      departureTime: "2023-05-15T10:30:00Z",
      arrivalTime: "2023-05-16T02:40:00Z",
      status: "delayed",
      scheduledDeparture: "10:30",
      estimatedDeparture: "13:30",
      scheduledArrival: "02:40",
      estimatedArrival: "05:40",
      delayMinutes: 180,
      delayReason: "Aircraft technical issue - Engine failure",
    },
    currentFault: {
      id: "F-2023-0456",
      description: "Engine #2 failure - N1 rotation issue with FADEC fault indication",
      system: "Propulsion",
      subsystem: "Engine - GE90-115B",
      ataChapter: "ATA 72-00-00",
      estimatedResolution: "7 hours",
      reportedBy: "John Smith",
      assignedTo: "Maria Garcia",
      status: "In Progress",
      priority: "High",
      impactedFlights: ["AC016", "AC017"],
      delayImpact: "180 minutes",
      reportedTime: "2023-05-15T08:15:00Z",
      impact: "high",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "GE90-115B",
      totalFlightHours: 42560,
      totalCycles: 5230,
      manufactureDate: "2015-03-12",
      lastCCheck: "2022-11-05",
      nextCCheck: "2024-11-05",
    },
    defects: [
      {
        id: "DEF-2023-0126",
        description: "IFE system reset required for seats 23A-23F",
        system: "In-Flight Entertainment",
        subsystem: "Seat Electronics",
        ataChapter: "ATA 44-10-00",
        reportedDate: "2023-05-14T12:30:00Z",
        status: "open",
        priority: "low",
        estimatedResolution: "Next overnight stop",
        assignedTo: "IFE Technician",
        reportedBy: "Cabin Crew",
        location: "Economy Cabin - Row 23",
        category: "Non-MEL",
      },
      {
        id: "DEF-2023-0127",
        description: "APU bleed air valve slow to respond",
        system: "Auxiliary Power Unit",
        subsystem: "Bleed Air System",
        ataChapter: "ATA 49-50-00",
        reportedDate: "2023-05-13T16:20:00Z",
        status: "in-progress",
        priority: "medium",
        estimatedResolution: "36 hours",
        assignedTo: "APU Specialist",
        reportedBy: "Flight Crew",
        location: "APU Compartment",
        category: "MEL C",
      },
    ],
  },
  {
    id: "AC002",
    registration: "C-FIUV",
    type: "Boeing 787-9",
    status: "maintenance",
    location: "YYZ",
    gate: "F23",
    maintenanceStatus: {
      type: "C-Check",
      dueDate: "2023-05-20T00:00:00Z",
      completionPercentage: 65,
      estimatedCompletion: "May 18, 2023",
      assignedTechnicians: ["Robert Chen", "Sarah Johnson", "Miguel Hernandez"],
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "GEnx-1B",
      totalFlightHours: 28750,
      totalCycles: 3420,
      manufactureDate: "2017-08-25",
      lastCCheck: "2021-05-10",
      nextCCheck: "2023-05-20",
    },
    defects: [
      {
        id: "DEF-2023-0128",
        description: "APU start failure during ground operations",
        system: "Auxiliary Power Unit",
        subsystem: "APU - GTCP 331-350",
        ataChapter: "ATA 49-00-00",
        reportedDate: "2023-05-10T09:45:00Z",
        status: "in-progress",
        priority: "high",
        estimatedResolution: "Part of C-Check",
        assignedTo: "C-Check Team",
        reportedBy: "Ground Crew",
        location: "APU Compartment",
        category: "MEL B",
      },
      {
        id: "DEF-2023-0129",
        description: "Cabin pressure controller fault messages",
        system: "Environmental Control",
        subsystem: "Pressurization",
        ataChapter: "ATA 21-30-00",
        reportedDate: "2023-05-08T14:15:00Z",
        status: "in-progress",
        priority: "high",
        estimatedResolution: "Part of C-Check",
        assignedTo: "C-Check Team",
        reportedBy: "Flight Crew",
        location: "Avionics Bay",
        category: "MEL B",
      },
      {
        id: "DEF-2023-0130",
        description: "Cargo door seal wear beyond limits",
        system: "Doors",
        subsystem: "Cargo Doors",
        ataChapter: "ATA 52-30-00",
        reportedDate: "2023-05-12T11:30:00Z",
        status: "in-progress",
        priority: "medium",
        estimatedResolution: "Part of C-Check",
        assignedTo: "C-Check Team",
        reportedBy: "Maintenance",
        location: "Aft Cargo Door",
        category: "Non-MEL",
      },
    ],
  },
  {
    id: "AC003",
    registration: "C-GHPQ",
    type: "Airbus A330-300",
    status: "aog",
    location: "CDG",
    gate: "E24",
    flightPhase: "Pre-Departure",
    nextFlight: {
      flightNumber: "AC881",
      destination: "YYZ",
      departureTime: "2023-05-15T13:45:00Z",
      arrivalTime: "2023-05-15T22:15:00Z",
      status: "delayed",
      scheduledDeparture: "13:45",
      estimatedDeparture: "17:45",
      scheduledArrival: "22:15",
      estimatedArrival: "02:15",
      delayMinutes: 240,
      delayReason: "Engine oil pressure fluctuations detected during pre-flight checks",
    },
    currentFault: {
      id: "F-2023-0789",
      description: "Engine oil pressure fluctuations detected during pre-flight checks",
      system: "Propulsion",
      subsystem: "Engine - GE CF6-80E1",
      ataChapter: "ATA 79-00-00",
      estimatedResolution: "12 hours",
      reportedBy: "Carlos Rodriguez",
      assignedTo: "Ahmed Hassan",
      status: "In Progress",
      priority: "High",
      impactedFlights: ["AC881", "AC882"],
      delayImpact: "240 minutes",
      reportedTime: "2023-05-15T11:30:00Z",
      impact: "high",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "GE CF6-80E1",
      totalFlightHours: 36420,
      totalCycles: 4890,
      manufactureDate: "2016-06-18",
      lastCCheck: "2022-04-15",
      nextCCheck: "2024-04-15",
    },
    defects: [
      {
        id: "DEF-2023-0131",
        description: "Cabin air recirculation fan noise",
        system: "Environmental Control",
        subsystem: "Air Distribution",
        ataChapter: "ATA 21-50-00",
        reportedDate: "2023-05-12T08:45:00Z",
        status: "deferred",
        priority: "low",
        estimatedResolution: "Next A-Check",
        assignedTo: "Maintenance Planning",
        reportedBy: "Cabin Crew",
        location: "Mid Cabin",
        category: "Non-MEL",
        deferralRef: "DEF-2023-0046",
        deferredUntil: "2023-06-10T00:00:00Z",
      },
    ],
  },
  {
    id: "AC123",
    registration: "C-FKJA",
    type: "Boeing 737 MAX 8",
    status: "active",
    location: "YYC",
    gate: "B22",
    flightPhase: "Boarding",
    nextFlight: {
      flightNumber: "AC206",
      destination: "YVR",
      departureTime: "2023-05-15T14:20:00Z",
      arrivalTime: "2023-05-15T16:05:00Z",
      status: "on-time",
      scheduledDeparture: "14:20",
      scheduledArrival: "16:05",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "CFM LEAP-1B",
      totalFlightHours: 12450,
      totalCycles: 2840,
      manufactureDate: "2019-11-30",
      lastCCheck: "2023-01-15",
      nextCCheck: "2025-01-15",
    },
    defects: [
      {
        id: "DEF-2023-0132",
        description: "Passenger reading light inoperative at seat 14F",
        system: "Electrical Power",
        subsystem: "Lighting",
        ataChapter: "ATA 33-20-00",
        reportedDate: "2023-05-14T19:30:00Z",
        status: "deferred",
        priority: "low",
        estimatedResolution: "Next overnight maintenance",
        assignedTo: "Line Maintenance",
        reportedBy: "Cabin Crew",
        location: "Economy Cabin - Seat 14F",
        category: "Non-MEL",
        deferralRef: "DEF-2023-0047",
        deferredUntil: "2023-05-16T00:00:00Z",
      },
    ],
  },
  {
    id: "AC808",
    registration: "C-GEOU",
    type: "Airbus A220-300",
    status: "active",
    location: "YUL",
    gate: "A15",
    flightPhase: "Arriving",
    nextFlight: {
      flightNumber: "AC417",
      destination: "YYZ",
      departureTime: "2023-05-15T16:30:00Z",
      arrivalTime: "2023-05-15T17:45:00Z",
      status: "probable-delay",
      scheduledDeparture: "16:30",
      estimatedDeparture: "17:00",
      scheduledArrival: "17:45",
      estimatedArrival: "18:15",
      delayMinutes: 30,
      delayReason: "Late inbound aircraft",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "Pratt & Whitney PW1500G",
      totalFlightHours: 8760,
      totalCycles: 3210,
      manufactureDate: "2020-08-15",
      lastCCheck: "2022-09-20",
      nextCCheck: "2024-09-20",
    },
    defects: [
      {
        id: "DEF-2023-0133",
        description: "Weather radar occasional false returns",
        system: "Navigation",
        subsystem: "Weather Radar",
        ataChapter: "ATA 34-40-00",
        reportedDate: "2023-05-13T11:20:00Z",
        status: "in-progress",
        priority: "medium",
        estimatedResolution: "48 hours",
        assignedTo: "Avionics Specialist",
        reportedBy: "Flight Crew",
        location: "Flight Deck",
        category: "MEL C",
      },
    ],
  },
  {
    id: "AC456",
    registration: "C-GITS",
    type: "Airbus A321-200",
    status: "active",
    location: "LHR",
    gate: "T2-B32",
    flightPhase: "Departing",
    nextFlight: {
      flightNumber: "AC855",
      destination: "YYZ",
      departureTime: "2023-05-15T15:10:00Z",
      arrivalTime: "2023-05-15T23:40:00Z",
      status: "on-time",
      scheduledDeparture: "15:10",
      scheduledArrival: "23:40",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "CFM56-5B3/P",
      totalFlightHours: 32150,
      totalCycles: 6780,
      manufactureDate: "2014-05-22",
      lastCCheck: "2022-06-10",
      nextCCheck: "2024-06-10",
    },
  },
  {
    id: "AC789",
    registration: "C-FPCA",
    type: "Boeing 777-200LR",
    status: "active",
    location: "NRT",
    gate: "53",
    flightPhase: "Turnaround",
    nextFlight: {
      flightNumber: "AC002",
      destination: "YYZ",
      departureTime: "2023-05-15T17:30:00Z",
      arrivalTime: "2023-05-16T01:15:00Z",
      status: "on-time",
      scheduledDeparture: "17:30",
      scheduledArrival: "01:15",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "GE90-110B1",
      totalFlightHours: 45680,
      totalCycles: 4980,
      manufactureDate: "2013-11-08",
      lastCCheck: "2022-08-15",
      nextCCheck: "2024-08-15",
    },
  },
  {
    id: "AC555",
    registration: "C-GKWJ",
    type: "Boeing 787-8",
    status: "scheduled",
    location: "YYZ",
    gate: "D36",
    maintenanceStatus: {
      type: "Pre-Delivery Inspection",
      dueDate: "2023-05-18T00:00:00Z",
      completionPercentage: 0,
      estimatedCompletion: "May 18, 2023",
    },
    nextFlight: {
      flightNumber: "AC037",
      destination: "MEL",
      departureTime: "2023-05-18T23:55:00Z",
      arrivalTime: "2023-05-20T06:30:00Z",
      status: "on-time",
      scheduledDeparture: "23:55",
      scheduledArrival: "06:30",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "GEnx-1B",
      totalFlightHours: 0,
      totalCycles: 0,
      manufactureDate: "2023-04-30",
    },
  },
  {
    id: "AC654",
    registration: "C-FMXC",
    type: "Airbus A330-300",
    status: "maintenance",
    location: "YUL",
    gate: "A22",
    maintenanceStatus: {
      type: "Engine Replacement",
      dueDate: "2023-05-17T00:00:00Z",
      completionPercentage: 40,
      estimatedCompletion: "May 17, 2023",
      assignedTechnicians: ["Jean Tremblay", "David Wilson", "Aisha Patel"],
    },
    nextFlight: {
      flightNumber: "AC871",
      destination: "CDG",
      departureTime: "2023-05-17T19:40:00Z",
      arrivalTime: "2023-05-18T08:55:00Z",
      status: "on-time",
      scheduledDeparture: "19:40",
      scheduledArrival: "08:55",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "Rolls-Royce Trent 700",
      totalFlightHours: 38750,
      totalCycles: 5120,
      manufactureDate: "2015-09-12",
      lastCCheck: "2022-02-18",
      nextCCheck: "2024-02-18",
    },
  },
  {
    id: "AC321",
    registration: "C-GJWO",
    type: "Airbus A320-200",
    status: "active",
    location: "YEG",
    gate: "C22",
    flightPhase: "Boarding",
    nextFlight: {
      flightNumber: "AC243",
      destination: "YVR",
      departureTime: "2023-05-15T15:45:00Z",
      arrivalTime: "2023-05-15T17:30:00Z",
      status: "imminent-delay",
      scheduledDeparture: "15:45",
      estimatedDeparture: "16:15",
      scheduledArrival: "17:30",
      estimatedArrival: "18:00",
      delayMinutes: 30,
      delayReason: "Crew scheduling issue",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "CFM56-5B4/P",
      totalFlightHours: 28950,
      totalCycles: 7840,
      manufactureDate: "2016-03-25",
      lastCCheck: "2022-11-10",
      nextCCheck: "2024-11-10",
    },
  },
  {
    id: "AC245",
    registration: "C-FTJZ",
    type: "Boeing 787-9",
    status: "aog",
    location: "YYZ",
    gate: "D31",
    flightPhase: "Pre-Departure",
    nextFlight: {
      flightNumber: "AC872",
      destination: "FRA",
      departureTime: "2023-05-15T19:30:00Z",
      arrivalTime: "2023-05-16T09:15:00Z",
      status: "delayed",
      scheduledDeparture: "19:30",
      estimatedDeparture: "23:30",
      scheduledArrival: "09:15",
      estimatedArrival: "13:15",
      delayMinutes: 240,
      delayReason: "Hydraulic system pressure loss in Yellow system - Actuator replacement required",
    },
    currentFault: {
      id: "F-2023-0512",
      description: "Hydraulic system pressure loss in Yellow system - Actuator replacement required",
      system: "Hydraulics",
      subsystem: "Yellow Hydraulic System",
      ataChapter: "ATA 29-20-00",
      estimatedResolution: "4 hours",
      reportedBy: "Sarah Johnson",
      assignedTo: "Robert Chen",
      status: "In Progress",
      priority: "High",
      impactedFlights: ["AC872", "AC873"],
      delayImpact: "240 minutes",
      reportedTime: "2023-05-15T17:45:00Z",
      impact: "high",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "GEnx-1B",
      totalFlightHours: 18750,
      totalCycles: 2340,
      manufactureDate: "2019-06-12",
      lastCCheck: "2022-09-18",
      nextCCheck: "2024-09-18",
    },
    defects: [
      {
        id: "DEF-2023-0245",
        description: "Hydraulic actuator leakage at Yellow system primary pump",
        system: "Hydraulics",
        subsystem: "Yellow Hydraulic System",
        ataChapter: "ATA 29-20-00",
        reportedDate: "2023-05-15T17:30:00Z",
        status: "open",
        priority: "high",
        estimatedResolution: "4 hours",
        assignedTo: "Hydraulics Team",
        reportedBy: "Flight Crew",
        location: "Hydraulic Bay",
        category: "MEL B",
      },
      {
        id: "DEF-2023-0246",
        description: "Cabin temperature control inconsistent in Zone 3",
        system: "Environmental Control",
        subsystem: "Temperature Control",
        ataChapter: "ATA 21-50-00",
        reportedDate: "2023-05-14T12:15:00Z",
        status: "deferred",
        priority: "low",
        estimatedResolution: "Next A-Check",
        assignedTo: "ECS Team",
        reportedBy: "Cabin Crew",
        location: "Aft Cabin",
        category: "Non-MEL",
        deferralRef: "DEF-2023-0089",
        deferredUntil: "2023-06-01T00:00:00Z",
      },
    ],
  },
  {
    id: "AC118",
    registration: "C-GHPT",
    type: "Airbus A330-300",
    status: "aog",
    location: "YYZ",
    gate: "F65",
    flightPhase: "Arrival",
    nextFlight: {
      flightNumber: "AC791",
      destination: "LHR",
      departureTime: "2023-05-15T22:15:00Z",
      arrivalTime: "2023-05-16T10:30:00Z",
      status: "cancelled",
      scheduledDeparture: "22:15",
      scheduledArrival: "10:30",
      delayMinutes: 0,
      delayReason: "Aircraft removed from service due to engine fault",
    },
    currentFault: {
      id: "F-2023-0513",
      description: "Engine #1 N1 vibration exceeding limits - Borescope inspection required",
      system: "Propulsion",
      subsystem: "Engine - Rolls-Royce Trent 700",
      ataChapter: "ATA 72-00-00",
      estimatedResolution: "24 hours",
      reportedBy: "Carlos Rodriguez",
      assignedTo: "Engine Specialist Team",
      status: "In Progress",
      priority: "Critical",
      impactedFlights: ["AC791", "AC792"],
      delayImpact: "Flight cancelled",
      reportedTime: "2023-05-15T16:20:00Z",
      impact: "critical",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "Rolls-Royce Trent 700",
      totalFlightHours: 42680,
      totalCycles: 5890,
      manufactureDate: "2014-11-30",
      lastCCheck: "2022-03-15",
      nextCCheck: "2024-03-15",
    },
    defects: [
      {
        id: "DEF-2023-0247",
        description: "Engine #1 N1 vibration exceeding limits during cruise",
        system: "Propulsion",
        subsystem: "Engine - Rolls-Royce Trent 700",
        ataChapter: "ATA 72-00-00",
        reportedDate: "2023-05-15T16:10:00Z",
        status: "open",
        priority: "critical",
        estimatedResolution: "24 hours",
        assignedTo: "Engine Specialist Team",
        reportedBy: "Flight Crew",
        location: "Engine #1",
        category: "MEL A",
      },
      {
        id: "DEF-2023-0248",
        description: "APU bleed valve slow to respond",
        system: "Auxiliary Power Unit",
        subsystem: "Bleed Air System",
        ataChapter: "ATA 49-50-00",
        reportedDate: "2023-05-14T09:30:00Z",
        status: "deferred",
        priority: "medium",
        estimatedResolution: "Next B-Check",
        assignedTo: "APU Team",
        reportedBy: "Maintenance",
        location: "APU Compartment",
        category: "MEL C",
        deferralRef: "DEF-2023-0090",
        deferredUntil: "2023-06-15T00:00:00Z",
      },
    ],
  },
  {
    id: "AC356",
    registration: "C-GKWB",
    type: "Airbus A321-200",
    status: "active",
    location: "YYZ",
    gate: "D45",
    flightPhase: "Boarding",
    nextFlight: {
      flightNumber: "AC427",
      destination: "YVR",
      departureTime: "2023-05-15T18:45:00Z",
      arrivalTime: "2023-05-15T21:30:00Z",
      status: "delayed",
      scheduledDeparture: "18:45",
      estimatedDeparture: "20:15",
      scheduledArrival: "21:30",
      estimatedArrival: "23:00",
      delayMinutes: 90,
      delayReason: "Avionics system fault - Flight Management Computer reboot required",
    },
    currentFault: {
      id: "F-2023-0514",
      description: "Flight Management Computer system fault - Multiple restarts required",
      system: "Avionics",
      subsystem: "Flight Management System",
      ataChapter: "ATA 34-10-00",
      estimatedResolution: "1.5 hours",
      reportedBy: "Michael Wong",
      assignedTo: "Avionics Team",
      status: "In Progress",
      priority: "High",
      impactedFlights: ["AC427"],
      delayImpact: "90 minutes",
      reportedTime: "2023-05-15T18:00:00Z",
      impact: "medium",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "CFM56-5B3/P",
      totalFlightHours: 28450,
      totalCycles: 7120,
      manufactureDate: "2016-08-22",
      lastCCheck: "2022-10-05",
      nextCCheck: "2024-10-05",
    },
    defects: [
      {
        id: "DEF-2023-0249",
        description: "Flight Management Computer system fault - Multiple restarts required",
        system: "Avionics",
        subsystem: "Flight Management System",
        ataChapter: "ATA 34-10-00",
        reportedDate: "2023-05-15T18:00:00Z",
        status: "open",
        priority: "high",
        estimatedResolution: "1.5 hours",
        assignedTo: "Avionics Team",
        reportedBy: "Flight Crew",
        location: "Flight Deck",
        category: "MEL B",
      },
      {
        id: "DEF-2023-0250",
        description: "Passenger seat 14D recline mechanism stuck",
        system: "Cabin Interior",
        subsystem: "Passenger Seats",
        ataChapter: "ATA 25-21-00",
        reportedDate: "2023-05-15T17:30:00Z",
        status: "deferred",
        priority: "low",
        estimatedResolution: "Next overnight maintenance",
        assignedTo: "Cabin Maintenance",
        reportedBy: "Cabin Crew",
        location: "Economy Cabin - Row 14",
        category: "Non-MEL",
        deferralRef: "DEF-2023-0091",
        deferredUntil: "2023-05-16T00:00:00Z",
      },
    ],
  },
  {
    id: "AC475",
    registration: "C-FZUM",
    type: "Airbus A320-200",
    status: "active",
    location: "YYZ",
    gate: "B19",
    flightPhase: "Boarding",
    nextFlight: {
      flightNumber: "AC123",
      destination: "YVR",
      departureTime: "2023-05-15T16:15:00Z",
      arrivalTime: "2023-05-15T18:45:00Z",
      status: "on-time",
      scheduledDeparture: "16:15",
      scheduledArrival: "18:45",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "CFM56-5B4/P",
      totalFlightHours: 24680,
      totalCycles: 6230,
      manufactureDate: "2017-05-12",
      lastCCheck: "2022-07-18",
      nextCCheck: "2024-07-18",
    },
  },
  {
    id: "AC612",
    registration: "C-GKFC",
    type: "Boeing 737 MAX 8",
    status: "active",
    location: "YYC",
    gate: "B14",
    flightPhase: "Arriving",
    nextFlight: {
      flightNumber: "AC215",
      destination: "YYZ",
      departureTime: "2023-05-15T17:20:00Z",
      arrivalTime: "2023-05-15T23:05:00Z",
      status: "probable-delay",
      scheduledDeparture: "17:20",
      estimatedDeparture: "17:50",
      scheduledArrival: "23:05",
      estimatedArrival: "23:35",
      delayMinutes: 30,
      delayReason: "Air traffic congestion at destination",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "CFM LEAP-1B",
      totalFlightHours: 9850,
      totalCycles: 2140,
      manufactureDate: "2020-03-15",
      lastCCheck: "2023-02-10",
      nextCCheck: "2025-02-10",
    },
  },
  {
    id: "AC734",
    registration: "C-FSJH",
    type: "Airbus A220-300",
    status: "active",
    location: "YVR",
    gate: "C34",
    flightPhase: "Departing",
    nextFlight: {
      flightNumber: "AC184",
      destination: "YYC",
      departureTime: "2023-05-15T14:50:00Z",
      arrivalTime: "2023-05-15T17:20:00Z",
      status: "imminent-delay",
      scheduledDeparture: "14:50",
      estimatedDeparture: "15:20",
      scheduledArrival: "17:20",
      estimatedArrival: "17:50",
      delayMinutes: 30,
      delayReason: "Late arrival of inbound aircraft",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "Pratt & Whitney PW1500G",
      totalFlightHours: 7230,
      totalCycles: 2680,
      manufactureDate: "2021-01-25",
      lastCCheck: "2022-12-05",
      nextCCheck: "2024-12-05",
    },
  },
  {
    id: "AC892",
    registration: "C-GKQB",
    type: "Boeing 787-9",
    status: "active",
    location: "YYZ",
    gate: "B23",
    flightPhase: "Boarding",
    nextFlight: {
      flightNumber: "AC056",
      destination: "NRT",
      departureTime: "2023-05-15T13:40:00Z",
      arrivalTime: "2023-05-16T15:25:00Z",
      status: "on-time",
      scheduledDeparture: "13:40",
      scheduledArrival: "15:25",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "GEnx-1B",
      totalFlightHours: 15780,
      totalCycles: 1890,
      manufactureDate: "2019-08-30",
      lastCCheck: "2022-10-12",
      nextCCheck: "2024-10-12",
    },
  },
  {
    id: "AC567",
    registration: "C-FPQB",
    type: "Airbus A321-200",
    status: "active",
    location: "YUL",
    gate: "A34",
    flightPhase: "Turnaround",
    nextFlight: {
      flightNumber: "AC432",
      destination: "YYZ",
      departureTime: "2023-05-15T15:30:00Z",
      arrivalTime: "2023-05-15T16:45:00Z",
      status: "on-time",
      scheduledDeparture: "15:30",
      scheduledArrival: "16:45",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "CFM56-5B3/P",
      totalFlightHours: 26540,
      totalCycles: 5980,
      manufactureDate: "2016-11-18",
      lastCCheck: "2022-08-25",
      nextCCheck: "2024-08-25",
    },
  },
  {
    id: "AC238",
    registration: "C-FGKH",
    type: "Boeing 777-300ER",
    status: "active",
    location: "YVR",
    gate: "D56",
    flightPhase: "Boarding",
    nextFlight: {
      flightNumber: "AC007",
      destination: "HKG",
      departureTime: "2023-05-15T13:25:00Z",
      arrivalTime: "2023-05-16T17:10:00Z",
      status: "on-time",
      scheduledDeparture: "13:25",
      scheduledArrival: "17:10",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "GE90-115B",
      totalFlightHours: 38920,
      totalCycles: 4560,
      manufactureDate: "2015-07-22",
      lastCCheck: "2022-05-18",
      nextCCheck: "2024-05-18",
    },
  },
  {
    id: "AC419",
    registration: "C-FGPT",
    type: "Airbus A330-300",
    status: "active",
    location: "YYZ",
    gate: "B29",
    flightPhase: "Departing",
    nextFlight: {
      flightNumber: "AC849",
      destination: "LHR",
      departureTime: "2023-05-15T21:00:00Z",
      arrivalTime: "2023-05-16T09:15:00Z",
      status: "on-time",
      scheduledDeparture: "21:00",
      scheduledArrival: "09:15",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "GE CF6-80E1",
      totalFlightHours: 32450,
      totalCycles: 4120,
      manufactureDate: "2016-02-28",
      lastCCheck: "2022-07-10",
      nextCCheck: "2024-07-10",
    },
  },
  {
    id: "AC723",
    registration: "C-GFAH",
    type: "Boeing 737 MAX 8",
    status: "active",
    location: "YOW",
    gate: "B7",
    flightPhase: "Boarding",
    nextFlight: {
      flightNumber: "AC458",
      destination: "YYZ",
      departureTime: "2023-05-15T16:10:00Z",
      arrivalTime: "2023-05-15T17:15:00Z",
      status: "on-time",
      scheduledDeparture: "16:10",
      scheduledArrival: "17:15",
    },
    technicalInfo: {
      manufacturer: "Boeing",
      engineType: "CFM LEAP-1B",
      totalFlightHours: 8760,
      totalCycles: 2340,
      manufactureDate: "2020-09-15",
      lastCCheck: "2023-01-20",
      nextCCheck: "2025-01-20",
    },
  },
  {
    id: "AC651",
    registration: "C-FSDT",
    type: "Airbus A220-300",
    status: "active",
    location: "YHZ",
    gate: "C12",
    flightPhase: "Arriving",
    nextFlight: {
      flightNumber: "AC619",
      destination: "YYZ",
      departureTime: "2023-05-15T18:30:00Z",
      arrivalTime: "2023-05-15T20:15:00Z",
      status: "probable-delay",
      scheduledDeparture: "18:30",
      estimatedDeparture: "19:00",
      scheduledArrival: "20:15",
      estimatedArrival: "20:45",
      delayMinutes: 30,
      delayReason: "Weather conditions at destination",
    },
    technicalInfo: {
      manufacturer: "Airbus",
      engineType: "Pratt & Whitney PW1500G",
      totalFlightHours: 6840,
      totalCycles: 2450,
      manufactureDate: "2021-03-10",
      lastCCheck: "2023-01-15",
      nextCCheck: "2025-01-15",
    },
  },
]

export function getAircraftById(id: string) {
  return aircraftData.find((aircraft) => aircraft.id === id)
}

// Function to get AOG history for an aircraft
export function getAOGHistoryForAircraft(id: string) {
  // This is a placeholder - in a real app, you would fetch this from your data source
  const aogHistory = [
    // AC404/AC014 History
    {
      id: "AOG-2023-001",
      aircraftId: "AC014",
      date: "2023-05-15",
      status: "resolved",
      faultRelation: {
        faultId: "F-2023-0789",
        description: "Hydraulic system pressure loss in Green system - ECAM HYD G SYS LO PR",
        system: "Hydraulics",
        subsystem: "Green Hydraulic System",
        ata: "ATA 29-10-00",
        impact: "high",
        estimatedResolution: "4 hours",
        delayCausality: ["Pressure Transducer Fault", "Component Replacement Required", "AOG"],
        technicalDetails: {
          componentPN: "HYD-PT-2234A",
          serialNumber: "SN45678",
          manufacturer: "Parker Aerospace",
          maintenanceManualRef: "AMM 29-10-00 PB 401",
          troubleshootingRef: "TSM 29-10-00",
          melRef: "MEL 29-10-01",
          category: "Category B",
          testProcedure: "Hydraulic Pressure Test TP-HYD-001",
          faultCodes: [
            {
              code: "HYD-G-029",
              description: "Green system pressure below threshold",
              timestamp: "2023-05-15T16:15:00Z",
            },
            { code: "HYD-G-042", description: "Green pump pressure fluctuation", timestamp: "2023-05-15T16:17:00Z" },
          ],
          replacementParts: [
            {
              name: "Pressure Transducer",
              partNumber: "HYD-PT-2234A",
              quantity: 1,
              available: false,
              location: "AOG Order",
              condition: "New",
              leadTime: "6 hours",
            },
            {
              name: "O-Ring Seal",
              partNumber: "OR-2234-S",
              quantity: 2,
              available: true,
              location: "Main Hangar",
              condition: "New",
            },
          ],
          dispatchConditions: {
            canDispatchWithFault: false,
            restrictions: [
              "No dispatch permitted with complete Green system failure",
              "MEL relief not available for this specific fault",
            ],
            additionalRequirements: "Full system functionality must be restored before dispatch",
          },
          troubleshootingSteps: [
            {
              step: 1,
              description: "Perform visual inspection of hydraulic lines",
              status: "Completed",
              result: "No visible leaks",
            },
            { step: 2, description: "Check hydraulic fluid level", status: "Completed", result: "Normal" },
            {
              step: 3,
              description: "Perform pressure test using external test equipment",
              status: "Completed",
              result: "Pressure drop confirmed",
            },
          ],
        },
      },
      chatHistory: {
        groupId: "group-1-AC014-HYD",
        messages: [
          {
            id: "msg-1",
            senderId: "system",
            senderName: "System",
            text: "AOG incident created for AC014 (C-FMWY) - Hydraulic system pressure loss in Green system",
            timestamp: "2023-05-15T16:10:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-2",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "I'm heading to the aircraft now to assess the hydraulic issue",
            timestamp: "2023-05-15T16:12:00Z",
          },
          {
            id: "msg-3",
            senderId: "user-2",
            senderName: "Maria Garcia",
            role: "Hydraulics Specialist",
            text: "I'll join you with the diagnostic equipment. ECAM shows HYD G SYS LO PR warning.",
            timestamp: "2023-05-15T16:15:00Z",
          },
          {
            id: "msg-4",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "Initial assessment shows pressure transducer fault. We'll need a replacement part.",
            timestamp: "2023-05-15T16:30:00Z",
          },
          {
            id: "msg-5",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "I've checked inventory. The part is not in stock. I'll place an AOG order immediately.",
            timestamp: "2023-05-15T16:35:00Z",
          },
          {
            id: "msg-6",
            senderId: "system",
            senderName: "System",
            text: "AOG parts order #P-78901 has been placed for HYD-PT-2234A",
            timestamp: "2023-05-15T16:40:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-7",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Estimated delivery time for the part is 6 hours. ETA 22:40.",
            timestamp: "2023-05-15T16:45:00Z",
          },
          {
            id: "msg-8",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "I'll prepare the maintenance area and tools for replacement once the part arrives.",
            timestamp: "2023-05-15T17:00:00Z",
          },
          {
            id: "msg-9",
            senderId: "user-2",
            senderName: "Maria Garcia",
            role: "Hydraulics Specialist",
            text: "I've completed the troubleshooting steps. Confirmed it's the pressure transducer. Here's the diagnostic report.",
            timestamp: "2023-05-15T17:30:00Z",
            hasAttachment: true,
            attachment: {
              type: "file",
              name: "AC014_HYD_Diagnostic.pdf",
              size: "2.4 MB",
              mimeType: "application/pdf",
            },
          },
          {
            id: "msg-10",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Update: Part has shipped and is en route. Still on track for 22:40 delivery.",
            timestamp: "2023-05-15T18:15:00Z",
          },
          {
            id: "msg-11",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "I've notified the flight crew and passengers about the delay. New estimated departure time is 00:30.",
            timestamp: "2023-05-15T18:30:00Z",
          },
          {
            id: "msg-12",
            senderId: "system",
            senderName: "System",
            text: "AOG parts order #P-78901 has arrived at maintenance hangar",
            timestamp: "2023-05-15T22:35:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-13",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Part has arrived. Beginning replacement procedure now.",
            timestamp: "2023-05-15T22:40:00Z",
          },
          {
            id: "msg-14",
            senderId: "user-2",
            senderName: "Maria Garcia",
            role: "Hydraulics Specialist",
            text: "Assisting with the replacement. Estimated completion time is 1 hour.",
            timestamp: "2023-05-15T22:45:00Z",
          },
          {
            id: "msg-15",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Replacement complete. Performing pressure tests now.",
            timestamp: "2023-05-15T23:50:00Z",
          },
          {
            id: "msg-15.5",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Here's a photo of the replaced pressure transducer. You can see the damage on the old component.",
            timestamp: "2023-05-15T23:55:00Z",
            hasAttachment: true,
            attachment: {
              type: "image",
              name: "replaced_transducer.jpg",
              size: "1.2 MB",
              mimeType: "image/jpeg",
              thumbnailUrl: "/placeholder.svg?height=200&width=300",
            },
          },
          {
            id: "msg-16",
            senderId: "user-2",
            senderName: "Maria Garcia",
            role: "Hydraulics Specialist",
            text: "Pressure tests successful. Green hydraulic system is now operating within normal parameters.",
            timestamp: "2023-05-16T00:10:00Z",
          },
          {
            id: "msg-17",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "Final checks complete. Aircraft is cleared for departure. Paperwork has been submitted.",
            timestamp: "2023-05-16T00:20:00Z",
          },
          {
            id: "msg-18",
            senderId: "system",
            senderName: "System",
            text: "AOG incident F-2023-0789 has been resolved. Total downtime: 8 hours 10 minutes.",
            timestamp: "2023-05-16T00:25:00Z",
            isSystemMessage: true,
          },
        ],
      },
    },
    {
      id: "AOG-2023-002",
      aircraftId: "AC014",
      date: "2023-01-22",
      status: "resolved",
      faultRelation: {
        faultId: "F-2023-0078",
        description: "Landing gear proximity sensor fault",
        system: "Landing Gear",
        subsystem: "Proximity Sensors",
        ata: "ATA 32-30-00",
        impact: "high",
        estimatedResolution: "5 hours",
        delayCausality: ["Sensor Fault", "Component Replacement Required"],
        technicalDetails: {
          componentPN: "LG-PS-5678",
          serialNumber: "PS-SN-67890",
          manufacturer: "Safran",
          troubleshootingSteps: [
            {
              step: 1,
              description: "Perform sensor diagnostic test",
              status: "Completed",
              result: "Fault confirmed",
            },
            {
              step: 2,
              description: "Replace proximity sensor",
              status: "Completed",
              result: "Component replaced successfully",
            },
          ],
        },
      },
      chatHistory: {
        groupId: "group-2-AC014-LG",
        messages: [
          {
            id: "msg-1",
            senderId: "system",
            senderName: "System",
            text: "AOG incident created for AC014 (C-FMWY) - Landing gear proximity sensor fault",
            timestamp: "2023-01-22T08:15:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-2",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "I'm at the aircraft. EICAS shows landing gear proximity sensor fault.",
            timestamp: "2023-01-22T08:20:00Z",
          },
          {
            id: "msg-3",
            senderId: "user-5",
            senderName: "Sarah Johnson",
            role: "Avionics Specialist",
            text: "I'll join you to run diagnostics on the proximity sensor.",
            timestamp: "2023-01-22T08:25:00Z",
          },
          {
            id: "msg-4",
            senderId: "user-5",
            senderName: "Sarah Johnson",
            role: "Avionics Specialist",
            text: "Diagnostic test complete. Confirmed fault in the nose gear proximity sensor. Need replacement.",
            timestamp: "2023-01-22T09:15:00Z",
          },
          {
            id: "msg-5",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Checking inventory for part LG-PS-5678.",
            timestamp: "2023-01-22T09:20:00Z",
          },
          {
            id: "msg-6",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Part is available in our Toronto inventory. Sending to your location now.",
            timestamp: "2023-01-22T09:30:00Z",
          },
          {
            id: "msg-7",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Preparing for replacement. Will need approximately 2 hours once part arrives.",
            timestamp: "2023-01-22T09:45:00Z",
          },
          {
            id: "msg-7.5",
            senderId: "user-5",
            senderName: "Sarah Johnson",
            role: "Avionics Specialist",
            text: "I've attached the technical manual section for the proximity sensor replacement procedure.",
            timestamp: "2023-01-22T09:55:00Z",
            hasAttachment: true,
            attachment: {
              type: "file",
              name: "LG-PS-5678_Replacement_Procedure.pdf",
              size: "4.8 MB",
              mimeType: "application/pdf",
            },
          },
          {
            id: "msg-8",
            senderId: "system",
            senderName: "System",
            text: "Part LG-PS-5678 has been dispatched from inventory",
            timestamp: "2023-01-22T09:50:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-9",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Part has arrived at maintenance hangar.",
            timestamp: "2023-01-22T10:30:00Z",
          },
          {
            id: "msg-10",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Beginning replacement procedure now.",
            timestamp: "2023-01-22T10:35:00Z",
          },
          {
            id: "msg-11",
            senderId: "user-5",
            senderName: "Sarah Johnson",
            role: "Avionics Specialist",
            text: "Assisting with replacement and will perform calibration after installation.",
            timestamp: "2023-01-22T10:40:00Z",
          },
          {
            id: "msg-12",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Replacement complete. Ready for calibration.",
            timestamp: "2023-01-22T12:15:00Z",
          },
          {
            id: "msg-13",
            senderId: "user-5",
            senderName: "Sarah Johnson",
            role: "Avionics Specialist",
            text: "Calibration complete. Running final tests.",
            timestamp: "2023-01-22T12:45:00Z",
          },
          {
            id: "msg-14",
            senderId: "user-5",
            senderName: "Sarah Johnson",
            role: "Avionics Specialist",
            text: "All tests passed. Proximity sensor is functioning correctly.",
            timestamp: "2023-01-22T13:10:00Z",
          },
          {
            id: "msg-15",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "Final inspection complete. Aircraft is cleared for service. Documentation submitted.",
            timestamp: "2023-01-22T13:30:00Z",
          },
          {
            id: "msg-16",
            senderId: "system",
            senderName: "System",
            text: "AOG incident F-2023-0078 has been resolved. Total downtime: 5 hours 15 minutes.",
            timestamp: "2023-01-22T13:35:00Z",
            isSystemMessage: true,
          },
        ],
      },
    },
    // AC008 History with chat
    {
      id: "AOG-2023-003",
      aircraftId: "AC008",
      date: "2023-05-15",
      status: "in-progress",
      faultRelation: {
        faultId: "F-2023-0823",
        description: "Engine #1 starter motor failure - Unable to achieve N2 rotation",
        system: "Propulsion",
        subsystem: "Engine Starting System",
        ata: "ATA 80-11-00",
        impact: "high",
        estimatedResolution: "3.5 hours",
        delayCausality: ["Starter Motor Failure", "Component Replacement Required", "AOG"],
      },
      chatHistory: {
        groupId: "group-3-AC008-ENG",
        messages: [
          {
            id: "msg-1",
            senderId: "system",
            senderName: "System",
            text: "AOG incident created for AC008 (C-FNND) - Engine #1 starter motor failure",
            timestamp: "2023-05-15T14:20:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-2",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "I'm at the aircraft. Engine #1 starter is not achieving N2 rotation. Will begin troubleshooting.",
            timestamp: "2023-05-15T14:25:00Z",
          },
          {
            id: "msg-3",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "I'll join you shortly. Have you checked the starter electrical connections?",
            timestamp: "2023-05-15T14:30:00Z",
          },
          {
            id: "msg-4",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Yes, electrical connections are secure. Performing starter motor resistance test now.",
            timestamp: "2023-05-15T14:40:00Z",
          },
          {
            id: "msg-5",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Resistance test shows out of spec values. Starter motor needs replacement.",
            timestamp: "2023-05-15T15:00:00Z",
          },
          {
            id: "msg-5.5",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Here's the starter motor wiring schematic for reference.",
            timestamp: "2023-05-15T15:10:00Z",
            hasAttachment: true,
            attachment: {
              type: "image",
              name: "starter_motor_schematic.png",
              size: "850 KB",
              mimeType: "image/png",
              thumbnailUrl: "/placeholder.svg?height=300&width=400",
            },
          },
          {
            id: "msg-6",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Checking inventory for engine starter motor P/N ENG-STR-9876.",
            timestamp: "2023-05-15T15:05:00Z",
          },
          {
            id: "msg-7",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "We have one in stock at LAX maintenance. Dispatching it now.",
            timestamp: "2023-05-15T15:15:00Z",
          },
          {
            id: "msg-8",
            senderId: "system",
            senderName: "System",
            text: "Part ENG-STR-9876 has been dispatched from LAX inventory",
            timestamp: "2023-05-15T15:20:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-9",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "I've notified operations about the delay. Estimated repair time?",
            timestamp: "2023-05-15T15:30:00Z",
          },
          {
            id: "msg-10",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Once the part arrives, replacement should take about 2 hours plus testing.",
            timestamp: "2023-05-15T15:35:00Z",
          },
        ],
      },
    },
    // AC016 History
    {
      id: "AOG-2023-005",
      aircraftId: "AC016",
      date: "2023-05-15",
      status: "in-progress",
      faultRelation: {
        faultId: "F-2023-0456",
        description: "Engine #2 failure - N1 rotation issue with FADEC fault indication",
        system: "Propulsion",
        subsystem: "Engine - GE90-115B",
        ata: "ATA 72-00-00",
        impact: "high",
        estimatedResolution: "7 hours",
      },
      chatHistory: {
        groupId: "group-4-AC016-ENG",
        messages: [
          {
            id: "msg-1",
            senderId: "system",
            senderName: "System",
            text: "AOG incident created for AC016 (C-FGDT) - Engine #2 failure with FADEC fault",
            timestamp: "2023-05-15T09:10:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-2",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "On site at AC016. FADEC showing multiple fault codes. Beginning diagnostics.",
            timestamp: "2023-05-15T09:15:00Z",
          },
          {
            id: "msg-3",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "This is a critical issue. I'm contacting GE technical support for assistance.",
            timestamp: "2023-05-15T09:20:00Z",
          },
          {
            id: "msg-4",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "FADEC diagnostic shows fault in the fuel metering unit. Will need replacement.",
            timestamp: "2023-05-15T10:00:00Z",
          },
          {
            id: "msg-5",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "GE support confirms the diagnosis. They're expediting a replacement unit.",
            timestamp: "2023-05-15T10:30:00Z",
          },
          {
            id: "msg-6",
            senderId: "system",
            senderName: "System",
            text: "AOG parts order #P-92345 has been placed for GE90 Fuel Metering Unit",
            timestamp: "2023-05-15T10:35:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-7",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Part is being flown in from Chicago. ETA 4 hours.",
            timestamp: "2023-05-15T10:40:00Z",
          },
          {
            id: "msg-8",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "I'll prepare for the replacement. GE is sending a technical representative to assist.",
            timestamp: "2023-05-15T11:00:00Z",
          },
          {
            id: "msg-9",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Update: Part has arrived at the airport. Being transported to maintenance now.",
            timestamp: "2023-05-15T14:30:00Z",
          },
          {
            id: "msg-10",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "GE technical rep has arrived. We're ready to begin the replacement procedure.",
            timestamp: "2023-05-15T15:00:00Z",
          },
          {
            id: "msg-11",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Replacement in progress. Estimated completion in 2 hours.",
            timestamp: "2023-05-15T15:15:00Z",
          },
        ],
      },
    },
    // AC003 History
    {
      id: "AOG-2023-006",
      aircraftId: "AC003",
      date: "2023-05-14",
      status: "in-progress",
      faultRelation: {
        faultId: "F-2023-0789",
        description: "Engine oil pressure fluctuations detected during cruise",
        system: "Propulsion",
        subsystem: "Engine - GEnx-1B",
        ata: "ATA 79-00-00",
        impact: "high",
        estimatedResolution: "12 hours",
        delayCausality: ["Oil Pressure Sensor Fault", "Component Replacement Required", "AOG"],
      },
      chatHistory: {
        groupId: "group-5-AC003-ENG",
        messages: [
          {
            id: "msg-1",
            senderId: "system",
            senderName: "System",
            text: "AOG incident created for AC003 (C-FHNY) - Engine oil pressure fluctuations",
            timestamp: "2023-05-14T18:45:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-2",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "I'm at the aircraft. EICAS shows oil pressure fluctuations in Engine #1.",
            timestamp: "2023-05-14T18:50:00Z",
          },
          {
            id: "msg-3",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "I'll join you shortly. Let's check the oil system for any leaks first.",
            timestamp: "2023-05-14T18:55:00Z",
          },
          {
            id: "msg-4",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Oil system inspection complete. No visible leaks. Suspect oil pressure sensor issue.",
            timestamp: "2023-05-14T19:30:00Z",
          },
          {
            id: "msg-5",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "Let's test the sensor. I'll get the diagnostic equipment.",
            timestamp: "2023-05-14T19:35:00Z",
          },
          {
            id: "msg-6",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Sensor test complete. Readings are inconsistent. We'll need to replace it.",
            timestamp: "2023-05-14T20:15:00Z",
          },
          {
            id: "msg-7",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Checking inventory for oil pressure sensor OPS-123456.",
            timestamp: "2023-05-14T20:20:00Z",
          },
          {
            id: "msg-8",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "We need to order the part. Estimated delivery time is 8 hours.",
            timestamp: "2023-05-14T20:30:00Z",
          },
          {
            id: "msg-9",
            senderId: "system",
            senderName: "System",
            text: "AOG parts order #P-45678 has been placed for OPS-123456",
            timestamp: "2023-05-14T20:35:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-10",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "I've notified operations. Flight AC016 will be delayed. Passengers are being informed.",
            timestamp: "2023-05-14T20:45:00Z",
          },
        ],
      },
    },
    // Historical AOG incidents for various aircraft
    {
      id: "AOG-2022-045",
      aircraftId: "AC014",
      date: "2022-10-14",
      status: "resolved",
      faultRelation: {
        faultId: "F-2022-0987",
        description: "Engine #2 starter motor failure",
        system: "Propulsion",
        subsystem: "Engine Starting System",
        ata: "ATA 80-11-00",
        impact: "high",
        estimatedResolution: "6 hours",
        delayCausality: ["Starter Motor Failure", "Component Replacement Required"],
      },
      chatHistory: {
        groupId: "group-5-AC014-ENG",
        messages: [
          {
            id: "msg-1",
            senderId: "system",
            senderName: "System",
            text: "AOG incident created for AC014 (C-FMWY) - Engine #2 starter motor failure",
            timestamp: "2022-10-14T11:30:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-2",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "At the aircraft now. Engine #2 starter is not functioning. Beginning diagnostics.",
            timestamp: "2022-10-14T11:40:00Z",
          },
          {
            id: "msg-3",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Starter motor has failed. Will need replacement.",
            timestamp: "2022-10-14T12:15:00Z",
          },
          {
            id: "msg-4",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Checking inventory for replacement starter motor.",
            timestamp: "2022-10-14T12:20:00Z",
          },
          {
            id: "msg-5",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "No starter in local inventory. Nearest one is in Montreal. Arranging transport.",
            timestamp: "2022-10-14T12:30:00Z",
          },
          {
            id: "msg-6",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "I've notified operations about the delay. Estimated 6 hours for repair once part arrives.",
            timestamp: "2022-10-14T12:45:00Z",
          },
          {
            id: "msg-7",
            senderId: "system",
            senderName: "System",
            text: "AOG parts order #P-65432 has been placed for Engine Starter Motor",
            timestamp: "2022-10-14T13:00:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-8",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Part is on flight AC1234 from Montreal. ETA 15:30.",
            timestamp: "2022-10-14T13:15:00Z",
          },
          {
            id: "msg-9",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "I've removed the faulty starter and prepared for installation of the new one.",
            timestamp: "2022-10-14T14:30:00Z",
          },
          {
            id: "msg-10",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Part has arrived and is being transported to the maintenance hangar.",
            timestamp: "2022-10-14T15:45:00Z",
          },
          {
            id: "msg-11",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Part received. Beginning installation now.",
            timestamp: "2022-10-14T16:00:00Z",
          },
          {
            id: "msg-12",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Installation complete. Performing initial tests.",
            timestamp: "2022-10-14T17:30:00Z",
          },
          {
            id: "msg-13",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Engine start test successful. Starter is functioning properly.",
            timestamp: "2022-10-14T18:00:00Z",
          },
          {
            id: "msg-14",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "Final checks complete. Aircraft is cleared for service. Documentation submitted.",
            timestamp: "2022-10-14T18:30:00Z",
          },
          {
            id: "msg-15",
            senderId: "system",
            senderName: "System",
            text: "AOG incident F-2022-0987 has been resolved. Total downtime: 7 hours.",
            timestamp: "2022-10-14T18:35:00Z",
            isSystemMessage: true,
          },
        ],
      },
    },
    {
      id: "AOG-2023-007",
      aircraftId: "AC001",
      date: "2023-03-22",
      status: "resolved",
      faultRelation: {
        faultId: "F-2023-0234",
        description: "APU fuel control unit malfunction",
        system: "Auxiliary Power Unit",
        subsystem: "Fuel Control",
        ata: "ATA 49-21-00",
        impact: "medium",
        estimatedResolution: "4 hours",
        delayCausality: ["Fuel Control Unit Fault", "Component Replacement Required"],
        technicalDetails: {
          componentPN: "APU-FCU-4567",
          serialNumber: "FCU-SN-12345",
          manufacturer: "Honeywell",
          troubleshootingSteps: [
            {
              step: 1,
              description: "Perform APU diagnostic test",
              status: "Completed",
              result: "FCU fault confirmed",
            },
            {
              step: 2,
              description: "Replace APU fuel control unit",
              status: "Completed",
              result: "Component replaced successfully",
            },
            {
              step: 3,
              description: "Perform APU start test",
              status: "Completed",
              result: "APU starts and runs normally",
            },
          ],
        },
      },
      chatHistory: {
        groupId: "group-6-AC001-APU",
        messages: [
          {
            id: "msg-1",
            senderId: "system",
            senderName: "System",
            text: "AOG incident created for AC001 (C-FGDT) - APU fuel control unit malfunction",
            timestamp: "2023-03-22T10:15:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-2",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "I'm at the aircraft. APU is failing to start. Beginning diagnostics.",
            timestamp: "2023-03-22T10:20:00Z",
          },
          {
            id: "msg-3",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "I'll join you to assist with the APU troubleshooting.",
            timestamp: "2023-03-22T10:25:00Z",
          },
          {
            id: "msg-4",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Diagnostic test complete. APU fuel control unit has failed. Need replacement.",
            timestamp: "2023-03-22T11:15:00Z",
          },
          {
            id: "msg-5",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Checking inventory for APU-FCU-4567.",
            timestamp: "2023-03-22T11:20:00Z",
          },
          {
            id: "msg-6",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "We have the part in stock. Sending it to your location now.",
            timestamp: "2023-03-22T11:30:00Z",
          },
          {
            id: "msg-7",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Preparing for replacement. Will need approximately 2 hours.",
            timestamp: "2023-03-22T11:45:00Z",
          },
          {
            id: "msg-8",
            senderId: "system",
            senderName: "System",
            text: "Part APU-FCU-4567 has been dispatched from inventory",
            timestamp: "2023-03-22T11:50:00Z",
            isSystemMessage: true,
          },
          {
            id: "msg-9",
            senderId: "user-4",
            senderName: "Lisa Chen",
            role: "Operations Manager",
            text: "Part has arrived at maintenance hangar.",
            timestamp: "2023-03-22T12:30:00Z",
          },
          {
            id: "msg-10",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Beginning replacement procedure now.",
            timestamp: "2023-03-22T12:35:00Z",
          },
          {
            id: "msg-11",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "Assisting with replacement and will perform testing after installation.",
            timestamp: "2023-03-22T12:40:00Z",
          },
          {
            id: "msg-12",
            senderId: "user-3",
            senderName: "Ahmed Hassan",
            role: "Mechanical Engineer",
            text: "Replacement complete. Ready for testing.",
            timestamp: "2023-03-22T14:15:00Z",
          },
          {
            id: "msg-13",
            senderId: "user-6",
            senderName: "Carlos Rodriguez",
            role: "Propulsion Specialist",
            text: "APU start test successful. Fuel control unit is functioning correctly.",
            timestamp: "2023-03-22T14:30:00Z",
          },
          {
            id: "msg-14",
            senderId: "user-1",
            senderName: "John Smith",
            role: "Lead Engineer",
            text: "Final inspection complete. Aircraft is cleared for service. Documentation submitted.",
            timestamp: "2023-03-22T14:45:00Z",
          },
          {
            id: "msg-15",
            senderId: "system",
            senderName: "System",
            text: "AOG incident F-2023-0234 has been resolved. Total downtime: 4 hours 30 minutes.",
            timestamp: "2023-03-22T14:50:00Z",
            isSystemMessage: true,
          },
        ],
      },
    },
  ]

  // Add AOG history for all aircraft with AOG status
  aircraftData.forEach((aircraft) => {
    if (aircraft.status === "aog" && !aogHistory.some((incident) => incident.aircraftId === aircraft.id)) {
      // Create a basic AOG history entry for this aircraft
      const currentDate = new Date().toISOString()
      const faultId = `F-2023-${aircraft.id}-001`

      aogHistory.push({
        id: `AOG-2023-${aircraft.id}`,
        aircraftId: aircraft.id,
        date: currentDate.split("T")[0],
        status: "in-progress",
        faultRelation: {
          faultId: faultId,
          description: aircraft.currentFault?.description || "Technical issue requiring maintenance",
          system: aircraft.currentFault?.system || "Unspecified",
          subsystem: aircraft.currentFault?.subsystem || "Unspecified",
          ata: aircraft.currentFault?.ataChapter || "Unspecified",
          impact: "high",
          estimatedResolution: "4-6 hours",
          delayCausality: ["Component Failure", "AOG"],
        },
        chatHistory: {
          groupId: `group-${aircraft.id}-AOG`,
          messages: [
            {
              id: "msg-1",
              senderId: "system",
              senderName: "System",
              text: `AOG incident created for ${aircraft.id} (${aircraft.registration}) - Technical issue`,
              timestamp: currentDate,
              isSystemMessage: true,
            },
            {
              id: "msg-2",
              senderId: "user-1",
              senderName: "John Smith",
              role: "Lead Engineer",
              text: `I'm heading to the aircraft to assess the issue.`,
              timestamp: new Date(new Date(currentDate).getTime() + 5 * 60000).toISOString(),
            },
            {
              id: "msg-3",
              senderId: "user-2",
              senderName: "Maria Garcia",
              role: "Technical Specialist",
              text: `I'll join you with the diagnostic equipment.`,
              timestamp: new Date(new Date(currentDate).getTime() + 10 * 60000).toISOString(),
            },
          ],
        },
      })
    }
  })

  // Add historical AOG incidents for all aircraft
  aircraftData.forEach((aircraft) => {
    if (!aogHistory.some((incident) => incident.aircraftId === aircraft.id && incident.date.startsWith("2022"))) {
      // Create a historical AOG entry from 2022
      const historicalDate = "2022-11-15T08:30:00Z"
      const faultId = `F-2022-${aircraft.id}-001`

      aogHistory.push({
        id: `AOG-2022-${aircraft.id}`,
        aircraftId: aircraft.id,
        date: "2022-11-15",
        status: "resolved",
        faultRelation: {
          faultId: faultId,
          description: "Avionics system fault - Navigation display malfunction",
          system: "Avionics",
          subsystem: "Navigation System",
          ata: "ATA 34-10-00",
          impact: "medium",
          estimatedResolution: "3 hours",
          delayCausality: ["Display Unit Failure", "Software Reset Required"],
        },
        chatHistory: {
          groupId: `group-${aircraft.id}-HIST`,
          messages: [
            {
              id: "msg-1",
              senderId: "system",
              senderName: "System",
              text: `AOG incident created for ${aircraft.id} (${aircraft.registration}) - Avionics system fault`,
              timestamp: historicalDate,
              isSystemMessage: true,
            },
            {
              id: "msg-2",
              senderId: "user-5",
              senderName: "Sarah Johnson",
              role: "Avionics Specialist",
              text: `I'm at the aircraft. Navigation display is showing incorrect data. Beginning diagnostics.`,
              timestamp: new Date(new Date(historicalDate).getTime() + 10 * 60000).toISOString(),
            },
            {
              id: "msg-3",
              senderId: "user-5",
              senderName: "Sarah Johnson",
              role: "Avionics Specialist",
              text: `Diagnostic test complete. Software reset required. Performing reset now.`,
              timestamp: new Date(new Date(historicalDate).getTime() + 45 * 60000).toISOString(),
            },
            {
              id: "msg-4",
              senderId: "user-5",
              senderName: "Sarah Johnson",
              role: "Avionics Specialist",
              text: `Reset complete. Navigation display functioning correctly. Running final tests.`,
              timestamp: new Date(new Date(historicalDate).getTime() + 90 * 60000).toISOString(),
            },
            {
              id: "msg-5",
              senderId: "user-1",
              senderName: "John Smith",
              role: "Lead Engineer",
              text: `Final checks complete. Aircraft is cleared for service. Documentation submitted.`,
              timestamp: new Date(new Date(historicalDate).getTime() + 120 * 60000).toISOString(),
            },
            {
              id: "msg-6",
              senderId: "system",
              senderName: "System",
              text: `AOG incident ${faultId} has been resolved. Total downtime: 2 hours 15 minutes.`,
              timestamp: new Date(new Date(historicalDate).getTime() + 135 * 60000).toISOString(),
              isSystemMessage: true,
            },
          ],
        },
      })
    }
  })

  return aogHistory.filter((incident) => incident.aircraftId === id)
}

// Function to get aircraft by station
export function getAircraftByStation(stationCode: string) {
  return aircraftData.filter((aircraft) => aircraft.location === stationCode)
}

// Function to get all AOG aircraft
export function getAOGAircraft() {
  return aircraftData.filter((aircraft) => aircraft.status === "aog")
}

// Function to get AOG aircraft by station
export function getAOGAircraftByStation(stationCode: string) {
  return aircraftData.filter((aircraft) => aircraft.status === "aog" && aircraft.location === stationCode)
}

// Function to get station statistics
export function getStationStatistics() {
  const stats = stations.map((station) => {
    const aircraftAtStation = aircraftData.filter((aircraft) => aircraft.location === station.code)
    const aogCount = aircraftAtStation.filter((aircraft) => aircraft.status === "aog").length
    const maintenanceCount = aircraftAtStation.filter((aircraft) => aircraft.status === "maintenance").length
    const activeCount = aircraftAtStation.filter((aircraft) => aircraft.status === "active").length
    const scheduledCount = aircraftAtStation.filter((aircraft) => aircraft.status === "scheduled").length

    return {
      station: station.code,
      stationName: station.name,
      totalAircraft: aircraftAtStation.length,
      aogCount,
      maintenanceCount,
      activeCount,
      scheduledCount,
      aogPercentage: aircraftAtStation.length > 0 ? (aogCount / aircraftAtStation.length) * 100 : 0,
      maintenancePercentage: aircraftAtStation.length > 0 ? (maintenanceCount / aircraftAtStation.length) * 100 : 0,
      activePercentage: aircraftAtStation.length > 0 ? (activeCount / aircraftAtStation.length) * 100 : 0,
      scheduledPercentage: aircraftAtStation.length > 0 ? (scheduledCount / aircraftAtStation.length) * 100 : 0,
    }
  })

  return stats
}

// Function to get all defects for an aircraft
export function getDefectsForAircraft(id: string) {
  const aircraft = getAircraftById(id)
  return aircraft?.defects || []
}

// Function to get maintenance history for an aircraft
export function getMaintenanceHistoryForAircraft(id: string) {
  // This would be fetched from a database in a real application
  // For now, we'll return a mock maintenance history
  return [
    {
      id: "MAINT-2023-001",
      aircraftId: id,
      type: "A-Check",
      startDate: "2023-01-15",
      endDate: "2023-01-16",
      location: "YYZ",
      status: "completed",
      technicians: ["John Smith", "Ahmed Hassan"],
      workItems: [
        {
          id: "WI-2023-001",
          description: "Routine inspection of flight controls",
          status: "completed",
          hours: 2,
        },
        {
          id: "WI-2023-002",
          description: "Engine oil change",
          status: "completed",
          hours: 3,
        },
      ],
    },
    {
      id: "MAINT-2022-045",
      aircraftId: id,
      type: "C-Check",
      startDate: "2022-08-10",
      endDate: "2022-08-20",
      location: "YUL",
      status: "completed",
      technicians: ["Maria Garcia", "Carlos Rodriguez", "Sarah Johnson"],
      workItems: [
        {
          id: "WI-2022-101",
          description: "Detailed structural inspection",
          status: "completed",
          hours: 24,
        },
        {
          id: "WI-2022-102",
          description: "Landing gear overhaul",
          status: "completed",
          hours: 16,
        },
        {
          id: "WI-2022-103",
          description: "Avionics systems check",
          status: "completed",
          hours: 8,
        },
      ],
    },
  ]
}
